---
name: CPAN-Reporter
version: 0.18
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: Provides Test::Reporter support for CPAN.pm
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CPAN: 1.88
  Config::Tiny: 2.08
  ExtUtils::MakeMaker: 0
  File::Basename: 0
  File::HomeDir: 0.58
  File::Path: 0
  File::Spec: 3.19
  File::Temp: 0.16
  File::pushd: 0.32
  IO::Capture: 0.05
  Probe::Perl: 0
  Tee: 0.13
  Test::More: 0.45
  Test::Reporter: 1.27
provides:
  CPAN::Reporter:
    file: lib/CPAN/Reporter.pm
    version: 0.18
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
