---
abstract: 'Adds CPAN Testers reporting to CPAN.pm'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Archive::Tar: 1.54
  File::Copy::Recursive: 0.35
  File::Spec::Functions: 0
  File::pushd: 0.32
  IO::CaptureOutput: 1.03
  List::Util: 0
  Test::Harness: 0
  Test::More: 0.62
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300033, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Reporter
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  CPAN::Reporter:
    file: lib/CPAN/Reporter.pm
    version: 1.2010
  CPAN::Reporter::API:
    file: lib/CPAN/Reporter/API.pm
    version: 1.2010
  CPAN::Reporter::Config:
    file: lib/CPAN/Reporter/Config.pm
    version: 1.2010
  CPAN::Reporter::FAQ:
    file: lib/CPAN/Reporter/FAQ.pm
    version: 1.2010
  CPAN::Reporter::History:
    file: lib/CPAN/Reporter/History.pm
    version: 1.2010
  CPAN::Reporter::PrereqCheck:
    file: lib/CPAN/Reporter/PrereqCheck.pm
    version: 1.2010
requires:
  CPAN: 1.9301
  CPAN::Version: 0
  Capture::Tiny: 0
  Carp: 0
  Config: 0
  Config::Tiny: 2.08
  Devel::Autoflush: 0.04
  Exporter: 0
  ExtUtils::MakeMaker: 6.36
  Fcntl: 0
  File::Basename: 0
  File::Find: 0
  File::Glob: 0
  File::HomeDir: 0.58
  File::Path: 0
  File::Spec: 3.19
  File::Temp: 0.16
  IO::File: 0
  IPC::Cmd: 0.76
  Parse::CPAN::Meta: 0
  Probe::Perl: 0
  Test::Reporter: 1.54
  constant: 0
  perl: 5.006
  strict: 0
  vars: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Reporter
  homepage: https://metacpan.org/release/CPAN-Reporter
  repository: git://github.com/dagolden/cpan-reporter.git
version: 1.2010
x_contributors:
  - 'Alexandr Ciornii <alexchorny@gmail.com>'
  - 'Breno G. de Oliveira <garu@cpan.org>'
  - 'Christian Walde <walde.christian@googlemail.com>'
  - 'Kent Fredric <kentfredric@gmail.com>'
  - 'Matthew Musgrove <mr.muskrat@gmail.com>'
