use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006007
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
cpanreporter
exe
metabase
na
skipfile
David
Golden
dagolden
Alexandr
Ciornii
alexchorny
Breno
de
Oliveira
garu
Christian
Walde
walde
Kent
Fredric
kentfredric
Matthew
Musgrove
mr
lib
CPAN
Reporter
FAQ
PrereqCheck
Config
API
History
