use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.002005
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok('bin', 'lib');
__DATA__
HTTPS
IRC
ISP's
MSWin
Modulino
SMTP
SSL
Skipfile
cpan
cpanreporter
exe
ini
metabase
modulino
na
uri
wiki
David
Golden
lib
CPAN
Reporter
History
Config
PrereqCheck
API
FAQ
